version: '3'
services:
  web:
    build: .
    command: npm start
    volumes:
      - .:/usr/app/
      - node_modules:/usr/app/node_modules
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    depends_on:
      - postgres
    environment:
      PORT: 3000
      DATABASE_URL: postgres://todoapp:supersecretpassword@postgres/todoapp
  postgres:
    image: postgres:11
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: todoapp
      POSTGRES_PASSWORD: supersecretpassword

volumes:
  postgres:
  node_modules:
