name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: node:14

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: todoapp
          POSTGRES_PASSWORD: supersecretpassword
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: Check out repository code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: npm ci

    - name: Migrate database
      run: npm run db:migrate
      env:
        DATABASE_URL: postgres://todoapp:supersecretpassword@postgres/todoapp

    - name: Run tests
      run: npm test
      env:
        PORT: 3000
        DATABASE_URL: postgres://todoapp:supersecretpassword@postgres/todoapp
